require_relative "x/version"

require "unicode/blocks"
require "unicode/categories"
require "unicode/confusable"
require "unicode/emoji"
require "unicode/display_width"
require "unicode/name"
require "unicode/sequence_name"
require "unicode/numeric_value"
require "unicode/scripts"
require "unicode/types"
